Use Cases - Regression
mlr-org/mlr-tutorial pull request #100
Opened 2017-03-12 19:04 UTC by pandeva

My first version of the regression use case. I would be glad about any feedback for improving it. (For example, I couldn't find a more elegant way to extract the tuned parameters.)

2017-03-12 19:26 UTC, gcskoenig reviewed
Great use case, added minor suggestions.

2017-03-12 19:26 UTC, gcskoenig commented on src/usecase_regression.Rmd
> +We have 14 numeric variables and as before ``medv`` is chosen to be the response variable for the regression model.
Consider starting a new sentence here, imo more readable:
The dataset contains 14 numeric variables. As before, ...

2017-03-12 19:26 UTC, gcskoenig commented on src/usecase_regression.Rmd
> +A closer look at the first boxplot reveals that random forest outperforms the other learners for this specific task. However, the SVM model using the measure ``mae`` seems to perform better than the
Not sure if "Moreover" is suitable in this context. Something like this: (?)
"In both cases, the benchmark experiments for linear and lasso regression models yield similar but poor results."

2017-03-12 22:31 UTC, pandeva commented on src/usecase_regression.Rmd
> +A closer look at the first boxplot reveals that random forest outperforms the other learners for this specific task. However, the SVM model using the measure ``mae`` seems to perform better than the
Thanks! :)

2017-03-13 12:41 UTC, schiffner requested changes
Hi, thx very much.

I left some comments regarding technical stuff.

Generally and with regard to your question: The model multiplexer optimizes over several learners and their parameters. So in contrast to other tuning methods it does't just decide on optimal parameters but also on the best out of several candidate learners. What you are doing in your use case, i.e. extracting optimal parameter values for *each* of the candidate learners is against the spirit of the model multiplexer.
My recommendation would be to change your example as follows:
* Make tuning wrappers for all candidate learners,
* Pass these tuning wrappers to benchmark.

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +We have 14 variables. As before, ``medv`` is chosen to be the response variable.
* The use case should be a stand-alone example. If the "As before" refers to another page in the tutorial I would remove it.
* I guess that most people will know this data set. But could you please explain shortly (just a sentence) what the Boston Housing is about and what the response variable `medv` means?

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +For the regression use case we use the well-known [Boston Housing](https://www.rdocumentation.org/packages/mlbench/versions/0.4-1/topics/BostonHousing) dataset. The road map is as follows:
* Please link to `[Boston Housing](&mlbench::BostonHousing)`.
* Please add here (or below) a sentence explaining what the data set is about and what you want to predict.

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +* define the learning task  ([here](http://mlr-org.github.io/mlr-tutorial/devel/html/task/index.html)),
* Please link to `[here](task.md)`.
* Same procedure for the links below.

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +```
* I think a `summary` would be nice, too.
* I would change the sentence in l.9 to "First, let's have a look at the data."

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +regr.task$task.desc$n.feat
I would remove l. 22 and just print the `regr.task`. The overview of feature types is included there.

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +By calling ``listLearners("regr")`` we can see which learners are available for the regression task. We picked the classical linear regression model (``regr.lm``), the [Lasso](https://www.rdocumentat
I would not link to the packages, but to the manual pages for the learners you use, for example `[Lasso](&glmnet::glmnet)`.

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +base.learners = list(
You could also use `makeLearners` here.

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +We start with specifying a search space for each parameter. Note that for all learners the hyperparameters, which will be tuned, should be positive. With [&makeTuneControlRandom] we set the tuning me
Could you please state which hyperparameters you are going to tune?

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +By calling ``listLearners("regr")`` we can see which learners are available for the regression task. We picked the classical linear regression model (``regr.lm``), the [Lasso](https://www.rdocumentat
Could you please update this paragraph? It seems that in your code below, you are using slightly different learners than stated above.

2017-03-13 12:41 UTC, schiffner commented on src/usecase_regression.Rmd
> +lrns = list(makeLearner("regr.lm"),
Could you please indent your code by 2 spaces?

2017-03-13 13:15 UTC, berndbischl commented
> The model multiplexer optimizes over several learners and their parameters.

please dont use the modelmultiplexer in these simpler usecases. 
it can maybe later be used in a complex tuning use case. but that should be separate.

2017-03-19 18:44 UTC, SteveBronder reviewed
Some of these review points are heuristic, feel free to change what you like. Overall very good!

2017-03-19 18:44 UTC, Stevo15025 commented on src/usecase_regression.Rmd
> +By calling ``listLearners("regr")`` we can see which learners are available for the regression task. We picked the classical linear regression model (``regr.lm``), the [Lasso](&penalized::penalized)
> , which we would like to compare

I would put this at the beginning of the sentence. Maybe something like

With so many learners it is difficult to choose which one would be optimal for this specific task. As such we will choose a sample of these learners and compare their results. This analysis uses...

2017-03-19 18:44 UTC, Stevo15025 commented on src/usecase_regression.Rmd
> +By calling ``listLearners("regr")`` we can see which learners are available for the regression task. We picked the classical linear regression model (``regr.lm``), the [Lasso](&penalized::penalized)
> The [%mlr] package provides powerful tuning algorithms.

list a few of them, we have quite a few high profile and powerful tuning methods that we can name drop here

2017-03-19 18:44 UTC, Stevo15025 commented on src/usecase_regression.Rmd
> +For each learner one hyperparameter will be tuned, i.e. the Lasso penalty parameter ``lambda1``, kernel parameter ``sigma`` for SVM model and the number of trees (``num.trees``) in the random forest
Mention to the reader that they find other parameters to tune using `getLearnerParamSet()`

2017-03-19 18:44 UTC, Stevo15025 commented on src/usecase_regression.Rmd
> +For each learner one hyperparameter will be tuned, i.e. the Lasso penalty parameter ``lambda1``, kernel parameter ``sigma`` for SVM model and the number of trees (``num.trees``) in the random forest
>  With [&makeTuneControlRandom] we set the tuning method to be random search. 

Random search is cool and good, but everyone else can do that too. It's simple and I like that, but maybe also do a tuning with mlrMBO or CMAES. Not necessary though

2017-03-19 18:44 UTC, Stevo15025 commented on src/usecase_regression.Rmd
> +tuned.lasso = makeTuneWrapper("regr.penalized.lasso", rdesc, meas, ps_lasso, ctrl)
for tutorials, I think it is good to explicitly name arguments when doing a function call

2017-03-19 20:57 UTC, pandeva commented on src/usecase_regression.Rmd
> +For each learner one hyperparameter will be tuned, i.e. the Lasso penalty parameter ``lambda1``, kernel parameter ``sigma`` for SVM model and the number of trees (``num.trees``) in the random forest
Thanks for your review! I will use CMAES. Should I discuss the input parameters of this method? Or it is enough to link the function (`makeTuneControlCMAES`) to the `cmaes` package.

2017-03-19 21:12 UTC, Stevo15025 commented on src/usecase_regression.Rmd
> +For each learner one hyperparameter will be tuned, i.e. the Lasso penalty parameter ``lambda1``, kernel parameter ``sigma`` for SVM model and the number of trees (``num.trees``) in the random forest
Going into too much detail could put the tutorial off track, just a link should be fine

2018-06-27 21:56 UTC, pat-s commented
superseeded by https://github.com/mlr-org/mlr/pull/2339

2018-06-27 21:56 UTC, closed without merging