add section for getOOBPreds
mlr-org/mlr-tutorial pull request #72
Opened 2017-01-27 11:03 UTC by PhilippPro

and also added it to the create learner section. This can be merged as soon as the function is available in the mlr master branch.

2017-01-27 12:09 UTC, schiffner commented
Cool, thanks!!

I can review next week.

2017-01-27 17:22 UTC, berndbischl commented
thanks to both of you

2017-03-06 17:21 UTC, schiffner requested changes
Many thanks. I had a lot of small comments, but nothing serious.

I restarted the Travis build and it failed with the error that `listLearner` doesn't know property "oobpreds". Not sure what is going on. Locally it works for me.

2017-03-06 17:21 UTC, schiffner commented on mkdocs.yml
>  - Extend:
Could you please change the file name to `out_of_bag_predictions.md`?

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +Some learners like random forest use bagging. Bagging means that the learner consists of a ensemble of several base learners and each base learner is trained with a different subsample or bootstrap s
an ensemble

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +
I would replace "to incorporate these predictions in the mlr framework." by
"to access these predictions.".

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +
provides OOB predictionS

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +* implement a new S3 method for function [&getOOBPreds] (which later is called
I guess the function name is `getOOBPredsLearner`

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +It must return the predictions in the same format as the predictLearner function.
Please link to `predictLearner`.

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +```{r, code=showFunctionDef(mlr:::getOOBPredsLearner.classif.randomForest = function(.learner, .model) {
This should just be
`showFunctionDef(mlr:::getOOBPredsLearner.classif.randomForest)`, i.e. no need to include the function body.

2017-03-06 17:21 UTC, schiffner commented on src/out-of-bag_predictions.Rmd
> +# Out-of-bag predictions
Please capitalize the title

2017-03-06 17:21 UTC, schiffner commented on src/out-of-bag_predictions.Rmd
> +Some learners like random forest use bagging. Bagging means that the learner consists of a ensemble of several base learners and each base learner is trained with a different random subsample or boot
an ensemble

2017-03-06 17:21 UTC, schiffner commented on src/out-of-bag_predictions.Rmd
> +
Same comment as for the create_learner page

2017-03-06 17:21 UTC, schiffner commented on src/out-of-bag_predictions.Rmd
> +To get the list of learners that provide OOB predictions, you can call listLearners(obj = NA, properties = "oobpreds").
Could you please add ` around the listLearners call?

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +
I would replace "you want to incorporate this in mlr" by something more specific like
"you want to readily access them via [&getOOBPreds]"

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +that was used in the training process, one can predict the observation with all base learners, where this observation was not used
The sentence starting with "For predicting an observation, ..." seems a little complicated.
My proposal would be: "A prediction made for an observation in the original data set using only base learners not trained on this particular observation is called out-of-bag (OOB) prediction."

2017-03-06 17:21 UTC, schiffner commented on src/create_learner.Rmd
> +overfitting, as the predictions where not made with learners that used the observation for training.
This whole text block (l. 469 - 472) is also on the Out-of-bag-predictions page.
I would remove it here and just concentrate on the technical stuff (starting with l. 474).

2017-03-07 14:46 UTC, schiffner reviewed
Hi Philipp, thanks very much. Found just one small thing. Could you please change this, then I will merge.

2017-03-07 14:46 UTC, schiffner commented on src/out_of_bag_predictions.Rmd
>  overfitting, as the predictions where not made with learners that used the observation for training.
The "called out-of-bag-predictions" part is now duplicated.

2017-03-07 18:08 UTC, schiffner approved these changes

2017-03-07 18:09 UTC, schiffner commented
Hi Philipp. Thanks again! Merging.

2017-03-07 18:10 UTC, merged