Quickstart
mlr-org/mlr-tutorial pull request #85
Opened 2017-03-08 15:29 UTC by engelhardtk

I tried to make the quickstart page more intuitive and show the general 3 steps of fitting a model.

2017-03-08 19:07 UTC, schiffner requested changes
Thx very much! I left a few comments.

2017-03-08 19:07 UTC, schiffner commented on src/index.Rmd
>  ```
You need an additional empty last line. This is why the Travis build failed.

2017-03-08 19:07 UTC, schiffner commented on src/index.Rmd
> +## specify the type of the analysis (e.g. classification), data and response
* Please capitalize the first word in the comments (here and also below)
* I would make it a whole sentence like this: "Specify ... (e.g. classification) and provide data and response variable"

2017-03-08 19:07 UTC, schiffner commented on src/index.Rmd
> +## choose a specific algorithm (e.g.linear discriminant analysis)
missing space between e.g. and linear

2017-03-08 19:07 UTC, schiffner commented on src/index.Rmd
> +Applying a statistical algorithm with [%mlr] has a basic structure of 3 steps not depending on the specific model.
I don't know if I like the message of this sentence. Since mlr provides a unified interface to learning methods, essentially *none* of the applied steps depends on the specific model.
In the code example below the `predict` and `performance` also are always the same, regardless which learner was selected. So why of all things 3?

2017-03-08 19:07 UTC, schiffner commented on src/index.Rmd
> +Applying a statistical algorithm with [%mlr] has a basic structure of 3 steps not depending on the specific model.
I would suggest sth. like:
"Here we show the [%mlr] workflow to train, make predictions, and evaluate a learner on a classification problem. It consists of 5 basic steps that are independent of the particular learning problem and method."

Please feel free to change and improve!

2017-03-08 19:07 UTC, schiffner commented on src/index.Rmd
> +```{r,results='hide',warning=FALSE,message=FALSE}
I don't really understand why you chose these chunk options.

2017-03-08 19:07 UTC, schiffner commented on src/index.Rmd
> +## by combining learner and task
"Combining"  learner and task is a little unspecific.
Maybe sth. like: "Train the learner on the task"

2017-03-09 14:07 UTC, MasonGallo commented on src/index.Rmd
> +model = train(lrn, task, subset = seq(1, n, by = 2))
I would add a brief explanation why you use `subset` arg and what it's doing

2017-03-09 14:10 UTC, MasonGallo commented on src/index.Rmd
> +## 5) Performance evaluation
I would spell out mean misclassification error and accuracy

2017-03-09 14:19 UTC, MasonGallo commented on src/index.Rmd
> +Here we show the [%mlr] workflow to train, make predictions, and evaluate a learner on a classification problem. It consists of 5 basic steps that are independent of the particular learning problem a
Instead of "it consists...": "We walk through 5 basic steps that work on any learning problem or method supported by `mlr`."

2017-03-10 11:59 UTC, schiffner approved these changes

2017-03-10 15:03 UTC, schiffner commented
Thx all, merging.

2017-03-10 15:04 UTC, merged